[project]
name = "app"
version = "0.1.0"
description = "A simple Flask app"


[project.urls]
Home = "https://github.com/dabfid/dusza-regiister"

[build-system]
requires = ["flit_core>=3.2,<4", "wheel", "setuptools>=42"]
build-backend = "flit_core.buildapi"
