"""empty message

Revision ID: 11d5aeadba95
Revises: 51f908be52e4
Create Date: 2024-11-10 12:01:28.436131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d5aeadba95'
down_revision = '51f908be52e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('contact_name', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=60), nullable=False))
        batch_op.create_index(batch_op.f('ix_schools_password_hash'), ['password_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_username'))
        batch_op.drop_index(batch_op.f('ix_schools_password_hash'))
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_name')
        batch_op.drop_column('address')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
