"""migration2

Revision ID: 1b45f25bbc0e
Revises: 
Create Date: 2024-11-08 21:18:04.452633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b45f25bbc0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admins_password_hash'), ['password_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_admins_username'), ['username'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)

    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_languages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_languages_name'), ['name'], unique=True)

    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_name'), ['name'], unique=True)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('team_name', sa.String(length=30), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teammate1', sa.String(length=30), nullable=False),
    sa.Column('grade1', sa.Integer(), nullable=False),
    sa.Column('teammate2', sa.String(length=30), nullable=False),
    sa.Column('grade2', sa.Integer(), nullable=False),
    sa.Column('teammate3', sa.String(length=30), nullable=False),
    sa.Column('grade3', sa.Integer(), nullable=False),
    sa.Column('teammate_extra', sa.String(length=30), nullable=True),
    sa.Column('grade_extra', sa.Integer(), nullable=True),
    sa.Column('teachers', mysql.TEXT(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('language', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['language'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('team_name')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_password_hash'), ['password_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_username'))
        batch_op.drop_index(batch_op.f('ix_teams_password_hash'))
        batch_op.drop_index(batch_op.f('ix_teams_id'))

    op.drop_table('teams')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_name'))
        batch_op.drop_index(batch_op.f('ix_schools_id'))

    op.drop_table('schools')
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_languages_name'))
        batch_op.drop_index(batch_op.f('ix_languages_id'))

    op.drop_table('languages')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_username'))
        batch_op.drop_index(batch_op.f('ix_admins_password_hash'))
        batch_op.drop_index(batch_op.f('ix_admins_id'))

    op.drop_table('admins')
    # ### end Alembic commands ###
